import Head from 'next/head'
import styles from "../styles/Home.module.css";
import Switch from "@mui/material/Switch";
import Button from '@mui/material/Button';



const label = { inputProps: { "aria-label": "Switch demo" } };


export default function Home() {
  return (
    <>
      <Head>
        <title>RTSMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       

      </Head>


      <div className={styles.container}>
        <div>
          <span>With default Theme:</span>
        </div>
        <Switch {...label} defaultChecked />
        <Switch {...label} />
        <Switch {...label} disabled defaultChecked />
        <Button variant="contained">Hello World</Button>
      </div>
    </>
  )
}
